### ISSUE TITLE
Synthesis with ABC

### ISSUE THREAD

**Issue by lucageatti** [ltentrup/SafetySynth#4]
Hi,
when I ask only for (un)realizability of a circuit, the binary ./SafetySynth works well.
But when I ask also for synthesis it works only if called from the root directory of the project.
Did I make some mistakes during installation or do you have the same problem?

I think the problem is that it cannot resolve the path to the ABC tool.

Thanks.

**Comment by ltentrup** [comment]
You are right. Currently, the path to ABC is resolved according to the working directory. A workaround would be trying to resolve according to the $PATH environment variable. Thus, synthesis would work if ABC is installed.

**Comment by lucageatti** [comment]
Solved by #5
