### ISSUE TITLE
Troubles during compilation

### ISSUE THREAD

**Issue by lucageatti** [ltentrup/SafetySynth#6]
During the compilation of SafetySynth, I have the following issue when trying `make test`:
```
swift test
safetysynth: error: manifest parse error(s):
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/module.modulemap:1:8: error: redefinition of module 'AppleTextureEncoder'
module AppleTextureEncoder [system] [extern_c] {
       ^
/usr/local/include/module.modulemap:1:8: note: previously defined here
module AppleTextureEncoder [system] [extern_c] {
       ^
```

I tried it on macOS Catalina v. 10.15.6. 
Most likely, the update to Catalina caused this issue.

Do you have any idea about a workaround?

**Comment by ltentrup** [comment]
Compilation works for me on macOS 11.0 (my machine) and 10.15 (GitHub CI), maybe there is an unrelated issue? There are no tests, thus, `swift test` fails with `error: no tests found; create a target in the 'Tests' directory`.

**Comment by lucageatti** [comment]
Ok, then it is my update to MacOS Catalina the problem. Most likely, the update corrupted the installation of swift and/or its libraries. I will try to reinstall MacOS from scratch.
(I wrote `make test` because `make` takes a while, but also the latter has the same problem on my machine)

Since it seems a problem related to my own machine, I'll close the issue.

Thanks.
